# Generated by Django 4.0.1 on 2022-01-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name='station',
            name='lng',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
