# Generated by Django 4.0.1 on 2022-01-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_lat_alter_station_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='lng',
            field=models.FloatField(),
        ),
    ]
